spring.application.name=testProj
server.port=8080

# PostgreSQL Configuration (use env vars for flexibility)
spring.datasource.url=jdbc:postgresql://localhost:5432/registry_db
spring.datasource.username=registry_user
spring.datasource.password=registry_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#Redis configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000

# Registry File Path (keep for now, can remove later)
registry.file.path=./data/registry.json

# Health Check Configuration
health-check.interval-ms=15000
health-check.max-retries=2
health-check.failure-threshold=3
health-check.timeout-ms=5000
